version: '{build}'
image:
- Visual Studio 2017
- Ubuntu
environment:
  NUGETAPIKEY:
    secure: eBKIUm4YxcrbL3oVC/ZCBUA/inEu+7OMbKpgftpOc18ievKNwH8UAUB2t4w+89Xv
  APPVEYOR_YML_DISABLE_PS_LINUX: true
build_script:
- ps: .\build.ps1 --target=NuGetPublish """--trigger=$env:APPVEYOR_REPO_TAG_NAME""" "--nugetApiKey=$env:NUGETAPIKEY"
- sh: ./build.sh --target=NuGetPackage
test: off
artifacts:
- path: 'release\*.nupkg'
